### PR TITLE
08--surf+paddle+rwd

### PR DESCRIPTION
**Pull request by GarrettGraham**

### CODE REVIEW

**Comment by GarrettGraham** [comment]
WIP_https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/107

**Comment by GarrettGraham** [comment]
https://htmlpreview.github.io/?https://github.com/GarrettGraham/TIY-Assignments/blob/08--surf%2Bpaddle%2Brwd/pub/index.html

**Comment by GarrettGraham** [comment]
commented the link to the html preview...may take a while for the page to load

**Comment by al-the-x** [comment]
Well done cleaning up on this PR, Garrett. I'm sure it was a lot less confusing without all that cruft in there. I hope our pairing session today also helped you get on the right track for the next assignment. For all your protesting, you were quite proficient today. Maybe you should consider pairing up with Evan or Jared on the next assignment rather than working alone. You'll learn more by working with others and surprise yourself with what you're capable of doing.

**Pull request merged**
